using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoParts
{
    class Parts
    {
        static int AutoGeneratedNumber = 1;
        private int PartId, SupplierId;
        private string PartName;
        private decimal CostPerUnit;

        public Parts(string PartName, decimal CostPerUnit)
        {
            PartId1 = AutoGeneratedNumber++;
            PartName1 = PartName;
            CostPerUnit1 = CostPerUnit;
        }

        public int PartId1
        {
            get { return PartId; }
            set { PartId = value; }
        }

        public string PartName1
        {
            get { return PartName; }
            set
            {
                if (value.Length < 2 || value.Length > 20 || String.IsNullOrEmpty(value))
                {
                    throw new ArgumentException();
                }
                PartName = value;
            }
        }

        public decimal CostPerUnit1
        {
            get { return CostPerUnit; }
            set { CostPerUnit = value; }
        }
    }
}
